#include "pinmap.h"

void gpioPinAssignements(void)
{
	PIN_MAKE_INPUT(PEDAL);
	PIN_ENABLE_PULLUP(PEDAL);
	
	PIN_MAKE_INPUT(BUTTON_LEFT);
	PIN_ENABLE_PULLUP(BUTTON_LEFT);
	PIN_MAKE_INPUT(BUTTON_RIGHT);
	PIN_ENABLE_PULLUP(BUTTON_RIGHT);
	
	PIN_MAKE_INPUT(SELECTOR_1_A);
	PIN_ENABLE_PULLUP(SELECTOR_1_A);
	PIN_MAKE_INPUT(SELECTOR_1_B);
	PIN_ENABLE_PULLUP(SELECTOR_1_B);
	
	PIN_MAKE_INPUT(SELECTOR_2_A);
	PIN_ENABLE_PULLUP(SELECTOR_2_A);
	
	PIN_MAKE_INPUT(SELECTOR_3_A);
	PIN_ENABLE_PULLUP(SELECTOR_3_A);
	PIN_MAKE_INPUT(SELECTOR_3_B);
	PIN_ENABLE_PULLUP(SELECTOR_3_B);
	PIN_MAKE_INPUT(SELECTOR_3_C);
	PIN_ENABLE_PULLUP(SELECTOR_3_C);
	
	PIN_MAKE_OUTPUT(POWER_LED);
	PIN_MAKE_OUTPUT(STATUS_LED);
}
